/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface DataToChainInterface extends Interface {
  getFunction(nameOrSignature: "StoreData"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "RemarkMsg"): EventFragment;

  encodeFunctionData(
    functionFragment: "StoreData",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "StoreData", data: BytesLike): Result;
}

export namespace RemarkMsgEvent {
  export type InputTuple = [
    sender: AddressLike,
    timestamp: BigNumberish,
    data: BytesLike
  ];
  export type OutputTuple = [sender: string, timestamp: bigint, data: string];
  export interface OutputObject {
    sender: string;
    timestamp: bigint;
    data: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DataToChain extends BaseContract {
  connect(runner?: ContractRunner | null): DataToChain;
  waitForDeployment(): Promise<this>;

  interface: DataToChainInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  StoreData: TypedContractMethod<[_data: BytesLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "StoreData"
  ): TypedContractMethod<[_data: BytesLike], [void], "nonpayable">;

  getEvent(
    key: "RemarkMsg"
  ): TypedContractEvent<
    RemarkMsgEvent.InputTuple,
    RemarkMsgEvent.OutputTuple,
    RemarkMsgEvent.OutputObject
  >;

  filters: {
    "RemarkMsg(address,uint256,bytes)": TypedContractEvent<
      RemarkMsgEvent.InputTuple,
      RemarkMsgEvent.OutputTuple,
      RemarkMsgEvent.OutputObject
    >;
    RemarkMsg: TypedContractEvent<
      RemarkMsgEvent.InputTuple,
      RemarkMsgEvent.OutputTuple,
      RemarkMsgEvent.OutputObject
    >;
  };
}
